<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipiosEstadoMexico = [
            'Acambay',
            'Acolman',
            'Aculco',
            'Almoloya de Alquisiras',
            'Almoloya de Juárez',
            'Almoloya del Río',
            'Amanalco',
            'Amatepec',
            'Amecameca',
            'Apaxco',
            'Atenco',
            'Atizapán',
            'Atizapán de Zaragoza',
            'Atlacomulco',
            'Atlautla',
            'Axapusco',
            'Ayapango',
            'Calimaya',
            'Capulhuac',
            'Coacalco de Berriozábal',
            'Coatepec Harinas',
            'Cocotitlán',
            'Coyotepec',
            'Cuautitlán',
            'Cuautitlán Izcalli',
            'Donato Guerra',
            'Ecatepec de Morelos',
            'Ecatzingo',
            'Huehuetoca',
            'Hueypoxtla',
            'Huixquilucan',
            'Isidro Fabela',
            'Ixtapaluca',
            'Ixtapan de la Sal',
            'Ixtapan del Oro',
            'Ixtlahuaca',
            'Jaltenco',
            'Jilotepec',
            'Jilotzingo',
            'Jiquipilco',
            'Jocotitlán',
            'Joquicingo',
            'Juchitepec',
            'Lerma',
            'Malinalco',
            'Melchor Ocampo',
            'Metepec',
            'Mexicaltzingo',
            'Morelos',
            'Naucalpan de Juárez',
            'Nextlalpan',
            'Nezahualcóyotl',
            'Nicolás Romero',
            'Nopaltepec',
            'Ocoyoacac',
            'Ocuilan',
            'El Oro',
            'Otumba',
            'Otzoloapan',
            'Otzolotepec',
            'Ozumba',
            'Papalotla',
            'La Paz',
            'Polotitlán',
            'Rayón',
            'San Antonio la Isla',
            'San Felipe del Progreso',
            'San Martín de las Pirámides',
            'San Mateo Atenco',
            'San Simón de Guerrero',
            'Santo Tomás',
            'Soyaniquilpan de Juárez',
            'Sultepec',
            'Tecámac',
            'Tejupilco',
            'Temamatla',
            'Temascalapa',
            'Temascalcingo',
            'Temascaltepec',
            'Temoaya',
            'Tenancingo',
            'Tenango del Aire',
            'Tenango del Valle',
            'Teoloyucan',
            'Teotihuacán',
            'Tepetlaoxtoc',
            'Tepetlixpa',
            'Tepotzotlán',
            'Tequixquiac',
            'Texcaltitlán',
            'Texcalyacac',
            'Texcoco',
            'Tezoyuca',
            'Tianguistenco',
            'Timilpan',
            'Tlalmanalco',
            'Tlalnepantla de Baz',
            'Tlatlaya',
            'Toluca',
            'Tonatico',
            'Tultepec',
            'Tultitlán',
            'Valle de Bravo',
            'Valle de Chalco Solidaridad',
            'Villa de Allende',
            'Villa del Carbón',
            'Villa Guerrero',
            'Villa Victoria',
            'Xalatlaco',
            'Xonacatlán',
            'Zacazonapan',
            'Zacualpan',
            'Zinacantepec',
            'Zumpahuacán',
            'Zumpango'
        ];

        foreach ($municipiosEstadoMexico as $municipio) {
            Municipio::create([
                'nombre_municipio' => $municipio
            ]);
        }
    }
}